name: Backend (Go) Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache: false
          
      - name: Install dependencies and build
        working-directory: ./backend
        run: |
          go mod tidy
          go build -v

      - name: Run go vet
        working-directory: ./backend
        run: go vet ./...

      - name: Run go fmt
        working-directory: ./backend
        run: go fmt ./...

      - name: Run tests
        working-directory: ./backend
        run: go test ./...